version: '3.8'
services:
  nginx:
    build: ../nginx
    ports:
      - 1337:80
    depends_on:
      - reg4r
  reg4r:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:5000 app:app'
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:16.3
    restart: always
    env_file:
      - ./.env.prod.db
    ports:
      - 5432:5432
    volumes:
      - postgres_data_dmbc:/var/lib/postgresql/data/
volumes:
    postgres_data_dmbc:
            